# Generated by Django 4.0.4 on 2022-11-04 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0002_fooditem_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_img',
            field=models.CharField(max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='delivery_time',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rest',
            name='promo',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rest',
            name='res_img',
            field=models.CharField(max_length=222, null=True),
        ),
        migrations.CreateModel(
            name='Order_placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resdet', models.CharField(max_length=122, null=True)),
                ('fooddet', models.CharField(max_length=122, null=True)),
                ('userdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
